PLATFORM_IDENTIFIERS = {
  "Atari 2600": "nointro.atari-2600",
  "Atari 5200": "nointro.atari-5200",
  "Atari 7800": "nointro.atari-7800",
  "Nintendo - e-Reader": "nointro.e-reader",
  "Nintendo - Family Computer Disk System": "nointro.fds",
  "Nintendo - Game Boy": "nointro.gb",
  "Nintendo - Game Boy Advance": "nointro.gba",
  "Nintendo - Game Boy Advance (Multiboot)": "nointro.gba-multiboot",
  "Nintendo - Game Boy Color": "nointro.gbc",
  "Nintendo - Nintendo 64": "nointro.n64",
  "Nintendo - Nintendo 64DD": "nointro.n64dd",
  "Nintendo - Nintendo Entertainment System": "nointro.nes",
  "Nintendo - Pokemon-Mini": "nointro.poke-mini",
  "Nintendo - Super Nintendo Entertainment System (Combined)": "nointro.snes",
  "Nintendo - Virtual Boy": "nointro.vb",
  "NEC - PC Engine - TurboGrafx 16": "nointro.tg-16",
  "Sega - 32X": "nointro.32x",
  "Sega - Game Gear": "nointro.gg",
  "Sega - Master System - Mark III": "nointro.ms-mkiii",
  "Sega - Mega Drive - Genesis": "nointro.md",
}