# Form implementation generated from reading ui file 'd:\Python Projects\NoIntro Roms Downloader (Ui version)\ui\About.ui'
#
# Created by: PyQt6 UI code generator 6.4.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_About(object):
    def setupUi(self, About):
        About.setObjectName("About")
        About.resize(533, 242)
        About.setModal(True)
        self.gridLayout = QtWidgets.QGridLayout(About)
        self.gridLayout.setObjectName("gridLayout")
        self.author = QtWidgets.QLabel(About)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.author.sizePolicy().hasHeightForWidth())
        self.author.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        self.author.setFont(font)
        self.author.setObjectName("author")
        self.gridLayout.addWidget(self.author, 1, 1, 1, 1)
        self.program_title = QtWidgets.QLabel(About)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.program_title.sizePolicy().hasHeightForWidth())
        self.program_title.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(26)
        font.setBold(True)
        self.program_title.setFont(font)
        self.program_title.setAlignment(QtCore.Qt.AlignmentFlag.AlignLeading|QtCore.Qt.AlignmentFlag.AlignLeft|QtCore.Qt.AlignmentFlag.AlignTop)
        self.program_title.setObjectName("program_title")
        self.gridLayout.addWidget(self.program_title, 0, 1, 1, 1)
        self.logo = QtWidgets.QLabel(About)
        self.logo.setMinimumSize(QtCore.QSize(48, 48))
        self.logo.setMaximumSize(QtCore.QSize(48, 48))
        self.logo.setPixmap(QtGui.QPixmap(":/app.ico"))
        self.logo.setScaledContents(True)
        self.logo.setAlignment(QtCore.Qt.AlignmentFlag.AlignLeading|QtCore.Qt.AlignmentFlag.AlignLeft|QtCore.Qt.AlignmentFlag.AlignTop)
        self.logo.setObjectName("logo")
        self.gridLayout.addWidget(self.logo, 0, 0, 1, 1)
        self.description = QtWidgets.QLabel(About)
        self.description.setAlignment(QtCore.Qt.AlignmentFlag.AlignBottom|QtCore.Qt.AlignmentFlag.AlignLeading|QtCore.Qt.AlignmentFlag.AlignLeft)
        self.description.setOpenExternalLinks(True)
        self.description.setObjectName("description")
        self.gridLayout.addWidget(self.description, 2, 1, 1, 1)

        self.retranslateUi(About)
        QtCore.QMetaObject.connectSlotsByName(About)

    def retranslateUi(self, About):
        _translate = QtCore.QCoreApplication.translate
        About.setWindowTitle(_translate("About", "About..."))
        self.author.setText(_translate("About", "Made by Silv3r"))
        self.program_title.setText(_translate("About", "NoIntro Roms Downloader"))
        self.description.setText(_translate("About", "<html><head/><body><p>This program was made to easy access console\'s roms directly from <a href=\"https://archive.org\"><span style=\" font-weight:700; text-decoration: underline; color:#0000ff;\">archive.org</span></a>.<br/>I will try to add more systems on time. You can access to the actual list on <a href=\"https://github.com/silverlays/NoIntro-Roms-Downloader/platforms_list.py\"><span style=\" text-decoration: underline; color:#0000ff;\">this page</span></a><span style=\" font-style:italic;\">.</span></p><p><span style=\" font-style:italic;\">GitHub repository</span> : <a href=\"https://github.com/silverlays/NoIntro-Roms-Downloader\"><span style=\" font-weight:700; text-decoration: underline; color:#0000ff;\">github.com/silverlays/NoIntro-Roms-Downloader</span></a><span style=\" font-weight:700; font-style:italic;\"><br/></span><span style=\" font-style:italic;\">GitHub wiki</span> : <a href=\"https://github.com/silverlays/NoIntro-Roms-Downloader/wiki\"><span style=\" font-weight:700; text-decoration: underline; color:#0000ff;\">github.com/silverlays/NoIntro-Roms-Downloader/wiki</span></a><span style=\" font-weight:700; font-style:italic;\"><br/></span></p><p><span style=\" font-weight:700; font-style:italic;\">Have fun :)</span></p></body></html>"))
