# Form implementation generated from reading ui file 'd:\Python Projects\NoIntro Roms Downloader (Ui version)\ui\DownloadQueue.ui'
#
# Created by: PyQt6 UI code generator 6.4.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_DownloadQueue(object):
    def setupUi(self, DownloadQueue):
        DownloadQueue.setObjectName("DownloadQueue")
        DownloadQueue.resize(380, 512)
        self.listWidget = QtWidgets.QListWidget(DownloadQueue)
        self.listWidget.setGeometry(QtCore.QRect(0, 0, 381, 511))
        self.listWidget.setObjectName("listWidget")

        self.retranslateUi(DownloadQueue)
        QtCore.QMetaObject.connectSlotsByName(DownloadQueue)

    def retranslateUi(self, DownloadQueue):
        _translate = QtCore.QCoreApplication.translate
        DownloadQueue.setWindowTitle(_translate("DownloadQueue", "Download queue..."))
