# Form implementation generated from reading ui file 'd:\Python Projects\NoIntro Roms Downloader (Ui version)\ui\DownloadPane.ui'
#
# Created by: PyQt6 UI code generator 6.4.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_DownloadPane(object):
    def setupUi(self, DownloadPane):
        DownloadPane.setObjectName("DownloadPane")
        DownloadPane.resize(851, 68)
        self.verticalLayout = QtWidgets.QVBoxLayout(DownloadPane)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_3 = QtWidgets.QLabel(DownloadPane)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Maximum, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_3.sizePolicy().hasHeightForWidth())
        self.label_3.setSizePolicy(sizePolicy)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_2.addWidget(self.label_3)
        self.l_job = QtWidgets.QLabel(DownloadPane)
        self.l_job.setObjectName("l_job")
        self.horizontalLayout_2.addWidget(self.l_job)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.l_progress = QtWidgets.QLabel(DownloadPane)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Maximum, QtWidgets.QSizePolicy.Policy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.l_progress.sizePolicy().hasHeightForWidth())
        self.l_progress.setSizePolicy(sizePolicy)
        self.l_progress.setAlignment(QtCore.Qt.AlignmentFlag.AlignRight|QtCore.Qt.AlignmentFlag.AlignTrailing|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.l_progress.setObjectName("l_progress")
        self.horizontalLayout.addWidget(self.l_progress)
        self.pb_progress = QtWidgets.QProgressBar(DownloadPane)
        self.pb_progress.setProperty("value", 0)
        self.pb_progress.setTextVisible(False)
        self.pb_progress.setObjectName("pb_progress")
        self.horizontalLayout.addWidget(self.pb_progress)
        self.l_speed = QtWidgets.QLabel(DownloadPane)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.l_speed.sizePolicy().hasHeightForWidth())
        self.l_speed.setSizePolicy(sizePolicy)
        self.l_speed.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.l_speed.setObjectName("l_speed")
        self.horizontalLayout.addWidget(self.l_speed)
        self.verticalLayout.addLayout(self.horizontalLayout)

        self.retranslateUi(DownloadPane)
        QtCore.QMetaObject.connectSlotsByName(DownloadPane)

    def retranslateUi(self, DownloadPane):
        _translate = QtCore.QCoreApplication.translate
        DownloadPane.setWindowTitle(_translate("DownloadPane", "Form"))
        self.label_3.setText(_translate("DownloadPane", "Actual job :"))
        self.l_job.setText(_translate("DownloadPane", "N/A"))
        self.l_progress.setText(_translate("DownloadPane", "0/0"))
        self.l_speed.setText(_translate("DownloadPane", "0Kb/s"))
